# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./resources/ingress.yaml
- ./resources/dashboard-proxy-svc.yaml
- ./ingress/ingress-ns.yaml
patches: 
- path: ./patches/storage-class.yaml
- path: ./patches/indexer-resources.yaml
- path: ./patches/wazuh-resources.yaml
- path: ./patches/wazuh-master-resources.yaml
- path: ./patches/dashboard-svc.yaml
- path: ./patches/wazuh-master-svc.yaml
- path: ./patches/wazuh-workers-svc.yaml
helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  namespace: ingress-nginx
  version: 4.12.1
  valuesFile: ingress/values.yaml